### ISSUE TITLE
exeption if .env file have comment line

### ISSUE THREAD

**Issue by moroz-yuriy** [TheDragonCode/env-sync#4]
- Env Sync Version: 1.1.1
- PHP Version: 7.4.5
- Framework: Laravel

### Description:
Parser exception if .env file have comment line

### Steps To Reproduce:
Add to .env file comment at any line of file 
example:
```
# dev
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120
```

**Comment by andrey-helldar** [comment]
I have released version [1.2.0](https://github.com/andrey-helldar/env-sync/releases/tag/v1.2.0). The principle of collecting keys has been greatly changed in it. Now it does not copy the `.env` file to the `.env.example` file, erasing private data. The package now scans files for `env` and `getenv` calls and collects data from them.

The problem with previous versions was that the content of the keys in the two files had to be the same. This means that the main file must contain all the keys, not just those that need to be redefined. The update addresses this issue.

Update the package to the latest version and write whether an error will occur.

**Comment by moroz-yuriy** [comment]
In 1.2.0 all work fine!

**Comment by andrey-helldar** [comment]
Thank you!
